[project]
name = "modular-slam"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["scikit-build-core>=0.10", "pybind11>=2.12"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
cmake.args = ["--preset", "release-python-conan"]

[tool.scikit-build.wheel.packages]
modular_slam = "src/python/modular_slam"

[tool.scikit-build.cmake.define]
CMAKE_GENERATOR = "Ninja"
MODULAR_SLAM_BUILD_PYTHON_BINDINGS = "ON"
BUILD_TESTNG = "OFF"

[dependency-groups]
dev = [
    "pytest>=9.0.1",
]
