name: CMake

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [llvm-20, llvm-19, gcc-14]
        generator: [Ninja]
        build_type: [Release, RelWithDebInfo, Debug]
        include:
          - build_type: Release
            preset: conan-release
          - build_type: RelWithDebInfo
            preset: conan-relwithdebinfo
          - build_type: Debug
            preset: conan-debug
        exclude:
          - os: windows-latest
            compiler: gcc-14

    runs-on: ${{ matrix.os }}
    environment: modular-slam-ci

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows' )}}
          cmake: true
          conan: true
          ninja: true
          vcpkg: false
          clangtidy: ${{ env.CLANG_TIDY_VERSION }}
          gcovr: true

      - name: Install dependencies with conan
        shell: bash
        run: |
          conan profile detect
          conan install . --build=missing -of conan_build -s build_type=${{ matrix.build_type }}

      - name: Configure CMake
        shell: bash
        run: |
          echo "Using ${{ matrix.preset }}"
          cmake --preset=${{ matrix.preset }}  -DWARNINGS_AS_ERRORS=ON

      - name: Build
        shell: bash
        run: |
          cmake --build --preset=${{ matrix.preset }} -j

      - name: Test
        shell: bash
        run: |
          ctest --preset=${{ matrix.preset }} -j

      - name: Coverage
        shell: bash
        if: matrix.build_type == 'Debug' && contains(matrix.os, 'ubuntu')
        run: |
          mkdir coverage_report
          gcovr -j ${{env.nproc}} --exclude 'tests/.*' --print-summary --html --html-details -o coverage_report/index.html

  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run clang-format
        uses: jidicula/clang-format-action@v4.15.0
        with:
          clang-format-version: "20"
