name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    environment: modular-slam-ci
    container:
      image: ghcr.io/marcin-ochman/modular-slam:v0.0.10-conan
      credentials:
        username: marcin-ochman
        password: ${{ secrets.container_registry_token }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      shell: bash
      run:  mkdir build; cd build;  cmake -DCMAKE_TOOLCHAIN_FILE=/conan_install/build/Release/generators/conan_toolchain.cmake  -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_FLAGS="-Wall -pedantic -Wextra" ..; cd -

    - name: Build
      shell: bash
      run: cd build; source  /conan_install/build/Release/generators/conanrun.sh; make -j; cd -

    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: source  /conan_install/build/Release/generators/conanrun.sh; ctest -C ${{env.BUILD_TYPE}} --output-on-failure

    - name: Generate Docs
      run: cd build; make doc; cd -;
      if: endsWith(github.ref, 'master')

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      if: endsWith(github.ref, 'master')
      with:
        branch: gh-pages
        folder: build/doc/doxygen/html/
