name: CMake

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [llvm-20, llvm-19, gcc-14]
        preset: [release-test-conan, relwithdebinfo-test-conan, coverage-conan]
        sanitizer: [none, asan, ubsan, tsan]
        exclude:
          - os: windows-latest
            compiler: gcc-14
          - os: windows-latest
            sanitizer: tsan
          - os: windows-latest
            sanitizer: ubsan
          - os: windows-latest
            sanitizer: asan
          - preset: Release
            sanitizer: asan
          - preset: Release
            sanitizer: ubsan
          - preset: Release
            sanitizer: tsan

    runs-on: ${{ matrix.os }}
    environment: modular-slam-ci

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows' )}}
          cmake: true
          conan: true
          ninja: true
          vcpkg: false
          clangtidy: ${{ env.CLANG_TIDY_VERSION }}
          gcovr: true

      - name: Configure CMake
        shell: bash
        run: |
          case "${{ matrix.sanitizer }}" in
            asan) asan=ON;  ubsan=OFF; tsan=OFF ;;
            ubsan) asan=OFF; ubsan=ON;  tsan=OFF ;;
            tsan) asan=OFF; ubsan=OFF; tsan=ON  ;;
            *)    asan=OFF; ubsan=OFF; tsan=OFF ;;
          esac

          if [ "${{ matrix.sanitizer }}" = "none" ] && [ "${{ matrix.preset }}" = "Debug" ]; then
            COVERAGE="ON"
          else
            COVERAGE="OFF"
          fi

          if [[ "${{ matrix.compiler }}" == llvm-* ]]; then
            ENABLE_CLANG_TIDY="ON"
          else
            ENABLE_CLANG_TIDY="OFF"
          fi

          cmake \
            -G Ninja \
            --preset=${{ matrix.preset }} \
            -DMODULAR_SLAM_ENABLE_SANITIZER_ADDRESS=${asan} \
            -DMODULAR_SLAM_ENABLE_SANITIZER_UNDEFINED=${ubsan} \
            -DMODULAR_SLAM_ENABLE_SANITIZER_THREAD=${tsan} \
            -DMODULAR_SLAM_WARNINGS_AS_ERRORS=OFF \
            -DMODULAR_SLAM_ENABLE_COVERAGE=${COVERAGE} \
            -DMODULAR_SLAM_ENABLE_CLANG_TIDY=${ENABLE_CLANG_TIDY}

      - name: Build
        shell: bash
        run: |
          cmake --build build -j

      - name: Test
        shell: bash
        env:
          ASAN_OPTIONS: detect_leaks=1:strict_string_checks=1:abort_on_error=1:fast_unwind_on_malloc=0
          UBSAN_OPTIONS: print_stacktrace=1:halt_on_error=1
          TSAN_OPTIONS: halt_on_error=1:history_size=7
          LLVM_SYMBOLIZER_PATH: ${{ runner.tool_cache }}/LLVM/*/x64/bin/llvm-symbolizer.exe
        run: |
          ctest --test-dir build -j --output-on-failure

      - name: Coverage
        shell: bash
        if: matrix.preset == 'coverage-conan' && matrix.sanitizer == 'none' && contains(matrix.os, 'ubuntu')
        run: |
          mkdir coverage_report
          gcovr -j ${{env.nproc}} --exclude 'tests/.*' --print-summary --html --html-details -o coverage_report/index.html

  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run clang-format
        uses: jidicula/clang-format-action@v4.15.0
        with:
          clang-format-version: "20"
