name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    environment: modular-slam-ci
    container:
      image: ghcr.io/marcin-ochman/modular_slam:1.0.0-24102025-dev
      credentials:
        username: marcin-ochman
        password: ${{ secrets.container_registry_token }}

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install dependencies with conan
        shell: bash
        run: |
          conan profile detect
          conan install . --build=missing  -of conan_build
          source conan_build/build/Release/generators/conanbuild.sh

      - name: Configure CMake
        shell: bash
        run: |
          source conan_build/build/Release/generators/conanbuild.sh
          cmake --preset=conan-release -DWARNINGS_AS_ERRORS=ON

      - name: Build
        shell: bash
        run: |
          source conan_build/build/Release/generators/conanbuild.sh
          cmake --build --preset=conan-release -j

      - name: Test
        shell: bash
        run: |
          source conan_build/build/Release/generators/conanbuild.sh
          ctest --preset=conan-release
