name: Python

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python_version: ["3.10", "3.11", "3.12", "3.13"]

    runs-on: ${{ matrix.os }}
    environment: modular-slam-ci

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup Cpp
        uses: ./.github/actions/setup-cpp
        with:
          compiler: llvm-20
          os: ${{ matrix.os }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python_version }}

      - name: Build
        shell: bash
        run: |
          uv build

      - name: Test
        shell: bash
        run: |
          uv run -m pytest test/python
