name: Python

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python_version: ["3.10", "3.11", "3.12", "3.13"]

    runs-on: ${{ matrix.os }}
    environment: modular-slam-ci

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
